from flask import Blueprint, send_file, jsonify
from fpdf import FPDF
import io
from models import FlashcardDeck, StudySession, TaskItem, Course
from routes.study import token_required

export_bp = Blueprint('export', __name__)

@export_bp.route('/pdf/<int:deck_id>', methods=['GET'])
@token_required
def export_pdf(current_user, deck_id):
    deck = FlashcardDeck.query.filter_by(id=deck_id, user_id=current_user.id).first()
    if not deck:
        return jsonify({'error': 'Deck not found'}), 404
        
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=16, style='B')
    pdf.cell(200, 10, txt=f"Study Summary: {deck.title}", ln=True, align='C')
    pdf.ln(10)
    
    pdf.set_font("Arial", size=12)
    for i, card in enumerate(deck.cards, 1):
        try:
            front = card.front.encode('latin-1', 'replace').decode('latin-1')
            back = card.back.encode('latin-1', 'replace').decode('latin-1')
            
            pdf.set_font("Arial", size=12, style='B')
            pdf.multi_cell(0, 10, txt=f"Q{i}: {front}")
            pdf.set_font("Arial", size=12)
            pdf.multi_cell(0, 10, txt=f"A: {back}")
            pdf.ln(5)
        except Exception:
            pdf.multi_cell(0, 10, txt=f"Card {i} could not be rendered due to character encoding issues.")
            pdf.ln(5)
            
    # Save PDF to BytesIO
    pdf.output("temp_deck.pdf")
    with open("temp_deck.pdf", "rb") as f:
        pdf_bytes = f.read()
    mem = io.BytesIO(pdf_bytes)
    
    return send_file(
        mem,
        mimetype='application/pdf',
        as_attachment=True,
        download_name=f"{deck.title.replace(' ', '_')}_Notes.pdf"
    )

@export_bp.route('/study-report', methods=['GET'])
@token_required
def export_study_report(current_user):
    from sqlalchemy import func
    
    sessions = StudySession.query.filter_by(user_id=current_user.id).all()
    tasks = TaskItem.query.filter_by(user_id=current_user.id).all()
    courses = Course.query.filter_by(user_id=current_user.id).all()
    
    total_time = sum(s.duration_seconds for s in sessions)
    hrs = total_time // 3600
    mins = (total_time % 3600) // 60
    
    completed_tasks = sum(1 for t in tasks if t.is_completed)
    total_tasks = len(tasks)
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=20, style='B')
    pdf.cell(200, 15, txt=f"StudyPulse Pro Report", ln=True, align='C')
    pdf.set_font("Arial", size=14, style='I')
    pdf.cell(200, 10, txt=f"Student: {current_user.display_name or current_user.email}", ln=True, align='C')
    pdf.ln(10)
    
    pdf.set_font("Arial", size=16, style='B')
    pdf.cell(200, 10, txt="Overview Analytics", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 8, txt=f"Total Study Time: {hrs}h {mins}m", ln=True)
    pdf.cell(200, 8, txt=f"Task Completion: {completed_tasks} / {total_tasks} completed", ln=True)
    pdf.ln(10)
    
    pdf.set_font("Arial", size=16, style='B')
    pdf.cell(200, 10, txt="Active Courses", ln=True)
    pdf.set_font("Arial", size=12)
    if not courses:
        pdf.cell(200, 8, txt="No courses registered.", ln=True)
    else:
        for c in courses:
            pdf.cell(200, 8, txt=f"- {c.course_name} ({c.credit_hours} Credits, Goal Grade: {c.grade})", ln=True)
            
    pdf.ln(20)
    pdf.set_font("Arial", size=10, style='I')
    pdf.cell(200, 10, txt="Generated by StudyPulseAI", ln=True, align='C')
    
    pdf_bytes = pdf.output(dest='S').encode('latin1')
    mem = io.BytesIO(pdf_bytes)
    mem.seek(0)
    
    return send_file(
        mem,
        mimetype='application/pdf',
        as_attachment=True,
        download_name="StudyPulse_Pro_Report.pdf"
    )
